version: '3.7'

services:

  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx
    links:
      - php
    ports:
      - ${NGINX_PORT}:80
    restart: always
    volumes:
      - .:${SYMFONY_ROOT_DIR}:cached
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: ${SYMFONY_ROOT_DIR}

  php:
    build: docker/php
    container_name: php
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - ${PHP_PORT}:9000
    restart: always
    volumes:
      - .:${SYMFONY_ROOT_DIR}:cached
    working_dir: ${SYMFONY_ROOT_DIR}

volumes:
  db_data:
