version: '3.7'

services:

  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root #${MYSQL_ROOT_PASSWORD}
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx
    links:
      - php
    ports:
      - 8000:80 #${NGINX_PORT}:80
    restart: always
    volumes:
      - .:/var/www/SnowTricks:cached       #${SYMFONY_ROOT_DIR}
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf  #Ligne de base
      #- ./app/:/app // Nginx fonctionne mais sans volume copier
    working_dir: /var/www/SnowTricks  #${SYMFONY_ROOT_DIR}

  php:
    build: docker/php
    container_name: php
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 9000:9000 #${PHP_PORT}:9000
    restart: always
    volumes:
      - .:/var/www/SnowTricks:cached  #$.:{SYMFONY_ROOT_DIR}:cached
    working_dir: /var/www/SnowTricks #${SYMFONY_ROOT_DIR}

volumes:
  db_data:
